#! /bin/bash

image="lukebuk/mjs"
directory=$(pwd)
file=""
code=""

while getopts ":f:d:i:c:" opt; do
    case $opt in
        f)
            file=${OPTARG}
            ;;
        d)
            directory=$(cd "${OPTARG}"; pwd)
            ;;
        i)
            image=${OPTARG}
            ;;
        c)
            code=${OPTARG}
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
             exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ $file ]; then
    docker run --rm -v "$directory:/mjs-data" -w /mjs-data $image "$file"
fi

if [ $code ]; then
    docker run --rm $image -e "$code"
fi
